# 개발 서버 배포 설정
services:
  app:
    image: ${DOCKER_IMAGE}:IMAGE_TAG_PLACEHOLDER
    container_name: ${APPLICATION_NAME}
    env_file:
      - .env
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    networks:
      - external-net
    depends_on:
      - db
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
  # db 컨테이너만 실행 : docker compose up -d db
  db:
    image: mysql:8
    container_name: ${APPLICATION_NAME}-mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "${HOST_DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - external-net

volumes:
  mysql_data:

networks:
  external-net:
    external: true
    name: ${MMB_DOCKER_NETWORK}
