# 서버 관련 설정
server:
  port: ${SERVICE_PORT:8083}

# 스프링 부트 설정
spring:
  application:
    name: ${APPLICATION_NAME:mmb-member-question}

  datasource:
    # 데이터베이스 접속 URL
    # ${}는 환경 변수 값 또는 기본 값을 사용 (없으면 기본값 사용)
    url: jdbc:mysql://${DB_HOST:localhost}:${CONTAINER_DB_PORT:3306}/${DB_NAME:demo_db}
    # 데이터베이스 접속 사용자명
    username: ${DB_USERNAME:demo_user}
    # 데이터베이스 접속 비밀번호
    password: ${DB_PASSWORD:demo_password}
    # JDBC 드라이버 클래스 명
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      # Hibernate의 DDL(auto) 설정 (create, update, validate, none 등)
      ddl-auto: ${JPA_DDL_AUTO:update}
    # SQL 쿼리를 콘솔에 출력할지 여부
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        # SQL 포맷팅 여부 (가독성 좋게 출력)
        format_sql: ${JPA_FORMAT_SQL:true}
        # 사용할 데이터베이스 방언 설정 (MariaDB용)
        dialect: org.hibernate.dialect.MariaDBDialect

  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: mmb-question-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

# 로깅 레벨 설정
logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}  %-5level --- [%X{APPLICATION_NAME}] [traceId=%X{traceId:-}, spanId=%X{spanId:-}] %logger{36} : %msg%n"
  level:
    # 전체 애플리케이션의 기본 로그 레벨 (info, debug, warn, error 등)
    root: ${LOG_ROOT_LEVEL:info}
    # Spring Web 관련 로그 레벨
    org.springframework.web: ${LOG_WEB_LEVEL:debug}
    # 애플리케이션 패키지(com.demo) 관련 로그 레벨
    com.demo: ${LOG_APP_LEVEL:debug}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:mmb-zipkin}:${CONTAINER_ZIPKIN_PORT:9411}/api/v2/spans
